### ISSUE TITLE
Clarify that edition can be set in a Cargo workspace

### ISSUE THREAD

**Issue by djc** [rust-lang-nursery/edition-guide#45]
This seems to work, but is not mentioned in the guide (in `transitioning.html`):

```toml
cargo-features = ["edition"]

[workspace]
members = ["askama", "askama_derive", "askama_shared", "testing"]
edition = "2018"
```

Obviously, adding it one place instead of per-crate is rather attractive!
