### ISSUE TITLE
Document how edition 2018 handles optional dependencies without `extern crate`

### ISSUE THREAD

**Issue by orium** [rust-lang-nursery/edition-guide#96]
It is not clear how to handle optional dependencies now that `extern crate` is no longer need.

For instance, say we have a project that optionally uses serde if the feature `serde` is enabled.  This is how it was done before:

In `Cargo.toml`:
```toml
[dependencies]
serde = { version = "1", optional = true }
```

In `src/lib.rs`:
```rust
#[cfg(feature = "serde")]
extern crate serde;
```

The guide should explain how to address this.
